---

name: Build container from latest release
on:
  release:
    types:
      - created

jobs:
  docker-image-CI:
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Retag latest to backup
        uses: tinact/docker.image-retag@master
        with:
          image_name: clinicalgenomics/statina
          image_old_tag: latest
          image_new_tag: backup
          registry: registry.hub.docker.com
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: clinicalgenomics/statina
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ github.event.release.tag_name }}, latest"