name: NIPTool CI

on: ["pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # Set up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt

    - name: Coveralls Dependencies
      run: |
        pip install pytest-cov coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=NIPTool/
        coveralls
      env:
        GITHUB: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
